services:
  django:
    container_name: uas_lms
    build: .
    volumes:
      - ./code:/code
    ports:
      - "8001:8000"
    # command: sleep infinity
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres

  postgres:
    container_name: uas_db
    image: postgres:16
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5552:5432"
